# Generated by Django 5.0.3 on 2024-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keychain',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='clothes_images/'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keychain',
            name='image',
            field=models.ImageField(upload_to='keychain_images/'),
        ),
        migrations.AlterField(
            model_name='keychain',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='image',
            field=models.ImageField(upload_to='wallet_images/'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
