# Generated by Django 5.0.3 on 2024-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
