# Generated by Django 5.0.3 on 2024-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
