# Generated by Django 5.0.3 on 2024-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0007_order_products_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(default='[]'),
        ),
    ]
