# Generated by Django 5.0.3 on 2024-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0009_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(default='[]'),
        ),
    ]
