# Generated by Django 5.0.3 on 2024-04-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0011_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_price_after_gst',
        ),
    ]
