# Generated by Django 5.0.3 on 2024-04-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0014_rename_total_amount_order_total_price_after_gst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price_after_gst',
            new_name='total_price',
        ),
    ]
