# Generated by Django 5.0.6 on 2024-10-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0023_category_product_delete_belt_delete_clothes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.SlugField(default='default-category', unique=True),
        ),
    ]
