# Generated by Django 5.0.6 on 2024-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0024_category_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
