# Generated by Django 5.0.6 on 2024-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain_app', '0026_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
